stages:
  - build
  - run

image:
  name: docker.io/renovate/renovate

####
# docker run \
#     --rm \
#     -e LOG_LEVEL="debug" \
#     -e RENOVATE_TOKEN="${GITHUB_TOKEN}" \
#     -e RENOVATE_CONFIG_FILE="/renovate.json5" \
#     -e RENOVATE_DRY_RUN=false \
#     -e RENOVATE_REPOSITORIES="ruzickap/${PWD##*/}" \
#     -e RENOVATE_BASE_BRANCHES="$(git rev-parse --abbrev-ref HEAD)" \
#     -e RENOVATE_USERNAME="ruzickap" \
#     -e RENOVATE_GIT_AUTHOR="Renovate Bot <bot@renovateapp.com>" \
#     -v "${PWD}/.github/renovate.json5:/renovate.json5" \
#     renovate/renovate:"32.39.0"
###

###
#Regex tester 
#https://regex101.com/r/jIvHuy/2
###

renovate:
  variables:
    RENOVATE_CONFIG_FILE: $CI_PROJECT_DIR/config.json
    RENOVATE_BASE_DIR: $CI_PROJECT_DIR
    RENOVATE_ENDPOINT: $CI_API_V4_URL
    RENOVATE_PLATFORM: gitlab
    RENOVATE_GIT_AUTHOR: Renovate Bot <bot@renovateapp.com>
    RENOVATE_REQUIRE_CONFIG: 'true'
    RENOVATE_ONBOARDING: 'false'
    RENOVATE_IGNORE_PR_AUTHOR: 'true'
    LOG_LEVEL: info
    RENOVATE_TOKEN: ${GITLAB_TOKEN}
    RENOVATE_EXTRA_FLAGS: o1266/renovate-sample
  stage: build
  tags:
    - openshift
  script:
   # - renovate --token=${GITLAB_TOKEN} --endpoint=https://gitlab.com/api/v4 --platform=gitlab o1266/renovate-sample
    - renovate
